### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tartavull** [s-a/sublime-text-refactor#23]
How do I add a key binding to rename?

**Comment by s-a** [comment]
You can use Sublime Text userdefined key bindings in menu {Preferences / Key Bindings - User}. This is the entry I use to jump to a var definition ```{ "keys": ["f2"], "command": "gotodefinition", "args": {}}```  

Available command s are listes at [Context.sublime-menu](https://github.com/s-a/sublime-text-refactor/blob/master/Context.sublime-menu)

**Comment by tartavull** [comment]
Thanks! it does work for gotodefinition, but If I change the comand to rename, it doesn't

**Comment by s-a** [comment]
The command is ```renamevariable```

**Comment by tartavull** [comment]
that worked perfectly, thanks!
