### ISSUE TITLE
Support Command Palette?

### ISSUE THREAD

**Issue by joneshf** [s-a/sublime-text-refactor#25]
Any thoughts on adding support for the command palette? I'm not much of a mouse user, and I'm sure I'm not alone.

I figured I'd ask first instead of submitting a PR, but let me know and I'll throw one together.

**Comment by s-a** [comment]
You mean shortcuts right? There was a question regarding this at #23. let me know if this fits your needs.

**Comment by s-a** [comment]
An OK you mean ctrl+shift+p :smile_cat: . I ve never thought about this because I am using shortcuts. Is it not suggested there? Anyway PRs are welcome. Just create your own branch.
