### ISSUE TITLE
Can't find option to add node path

### ISSUE THREAD

**Issue by brenolf** [s-a/sublime-text-refactor#27]
I'm always getting "Node not found" error when trying to execute any command and I'm not able to find the configuration file shown on readme.

![screen shot 2015-07-16 at 2 48 56 pm](https://cloud.githubusercontent.com/assets/1520534/8730850/e2e0bb36-2bc9-11e5-9312-46ab967b428e.png)

**Comment by s-a** [comment]
Please try context menu

![image](https://cloud.githubusercontent.com/assets/1270662/8743529/ec9eff56-2c6f-11e5-9bd0-34079e95c552.png)
