### ISSUE TITLE
error whatever I do

### ISSUE THREAD

**Issue by gismoranas** [s-a/sublime-text-refactor#29]
sublimetext 3 on ubuntu 15, if I try to goto definition or rename a function (and probably something else also) I get this and nothing happens. In the preferences menu I have no entry for refactor settings, but the package is in the packages directory (with the settings file that has node as nodepath)

b'(node) util.error is deprecated. Use console.error instead.\nWARN: ERROR: Unexpected token: operator (>) [null:16,25]\n\n/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199\n    throw new JS_Parse_Error(message, line, col, pos);\n    ^\nError\n    at new JS_Parse_Error (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:185:18)\n    at js_error (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199:11)\n    at croak (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:630:9)\n    at token_error (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:638:9)\n    at unexpected (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:644:9)\n    at expr_atom (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:1125:9)\n    at maybe_unary (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:1281:19)\n    at expr_ops (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:1316:24)\n    at maybe_conditional (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:1321:20)\n    at maybe_assign (/home/alfred/.config/sublime-text-3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:1352:20)\n'

**Comment by s-a** [comment]
This indicates that your javascript code file contains a syntax error. I suggest to use some lint tool for sublime text.

**Comment by gismoranas** [comment]
are arrow functions supported? this line is causing it much probably:

event.on('data', data => writeFile(data, args));

**Comment by s-a** [comment]
No. Here is an issue regarding this https://github.com/s-a/sublime-text-refactor/issues/24
