### ISSUE TITLE
Node command not found

### ISSUE THREAD

**Issue by janbaer** [s-a/sublime-text-refactor#3]
Hello,

I just try it to use the rename command of your refactory plugin and I get the message that the node command is not found.

In my bash I can start node without problem. Do you expect any specific version?

Best regards

Jan

**Comment by scamden** [comment]
@s-a i'm getting this issue in sublime text 3, with the most recent install of this plugin, i also am on mac os x with `which node` reporting `/usr/local/bin/node` thoughts?

**Comment by s-a** [comment]
@scamden have you tried this? https://github.com/s-a/sublime-text-refactor#troubleshoot

**Comment by scamden** [comment]
what should i try? `node` should find the global installation on my path,
is there some other path i should set?

**Comment by scamden** [comment]
oops sorry, hard linking to the path works `{ "nodePath" :
"/usr/local/bin/node" }`

**Comment by s-a** [comment]
No problem. There are many tickets regarding node not found on mac. This is the reason I added this Option. I don ' t know why path settings are not respected by mac within Sublime Text.

**Comment by scamden** [comment]
Ya sorta weird. Either way glad it's fixed thanks!
