### ISSUE TITLE
Mocha test "should find within scope"

### ISSUE THREAD

**Issue by cvax** [s-a/sublime-text-refactor#31]
Hi,

I am on node v4.2.2 and mocha v2.3.4. When I run ``npm test`` it is failing on the "should find within scope" test. I tried increasing the timeout to 15000ms, but it fails as well. Any ideas? Thanks.

![Mocha Test](http://i.imgur.com/DpJnbcB.png)

**Comment by s-a** [comment]
Just tried the same and on my machine this works 
![image](https://cloud.githubusercontent.com/assets/1270662/13739689/f5e8854e-e9cc-11e5-8548-9e8b730ff3ca.png)
Using Mocha 2.3.4 too.

**Comment by aklef** [comment]
Also on windows. I had to do "npm install mocha", but after that it ran tests just fine for #31 and can confirm it passes. Running Sublime 3103

![image](https://cloud.githubusercontent.com/assets/1248568/13996823/bb638802-f105-11e5-9ac5-03e7bfd943fb.png)

**Comment by cvax** [comment]
Reinstalled latest version and the test passes. Thanks.
