### ISSUE TITLE
/bin/sh: node: command not found

### ISSUE THREAD

**Issue by eheiser** [s-a/sublime-text-refactor#6]
I have node installed but I keep getting a "/bin/sh: node: command not found" whenever I try to use refactor in sublimetext2. Any suggestions?
I'm on MacOSX 10.8.3

**Comment by vasiliyb** [comment]
for folks using nvm:
```
ln -s /Users/blah/.nvm/versions/node/v8.9.3/bin/node /usr/local/bin/node
```
unfortunately ;(
